input_blocks = """autoci@Controls autogenerated correlation calculations
basis@Basis sets are specified
casscf@Control of CASSCF/NEVPT2 and DMRG calculations
cipsi@Control of Iterative-Configuration Expansion Configuration Interaction calculation
cim@Control of Cluster In Molecules calculations
cis@Control of CIS and TD-DFT calculations (synonym is tddft)
chelpg@Control of the CHELPG (CHarges from ELectrostatic Potentials using a Grid-based method) atomic charge calculation scheme.
tddft@Control of CIS and TD-DFT calculations (synonym is cim)
coords@Input of atomic coordinates
cpcm@Control of the Conductor-like Polarizable Continuum Models
pointcharges@Control of the file containing the point charges for the electrostatic interaction
elprop@Control of electric property calculations
eprnmr@Control of EPR and NMR calculations
esd@Control of ESD calculations
freq@Control of frequency calculations
geom@Control of geometry optimization
loc@Localization of orbitals
mcrpa@Control CASSCF linear response calculations
md@Control of molecular dynamics simulation
mdci@Controls single reference correlation methods
method@Here a computation method is specified
mp2@Controls the details of the MP2 calculation
mrcc@Control of multi-reference CC calculations
mrci@Control of MRCI calculations
mtr@Control of normal mode trajectory run
conical@Control of conical intersection seam-space between two states
mm@Control of MM calculation 
numgrad@Control of numerical gradients
nbo@Controls NBO analysis with GENNBO
output@Control of output
pal@Control of parallel jobs
paras@Input of semi-empirical parameters
plots@Control of plot generation
qmmm@Control of the additive QM/MM calculation
rel@Control of relativistic options
rocis@Control of restricted-open-shell CIS
rr@Control of resonance Raman and absorption/fluorescence band-shape calculations
scf@Control of the SCF procedure
symmetry@Control of spatial symmetry recognition
sym@Control of spatial symmetry recognition
maxcore@Amount of scratch memory in MB that gets used
pal@Control how many parallel procceses get ran.
esd@Control of the Excited State Dynamics (ESD) module
moinp@Control of the GBW file that contains MOs to be read
neb@Control of the Nudge Elastic Band Optimizer settings
vpt2@Control settings of Valence State Perturbation Theory
fit@Control of the fitting options
sim@Control of the optional parameters for simulation
"""


settings_autoci_convergence = {
    # converger details
    "stol": ("Residue convergence tolerance,", 1e-06),
    "maxiter": ("maximum number of iterations until convergence", 50),
    "maxdiis": ("depth of the DIIS memory", 5),
    "diisstartiter": ("Apply DIIS starting at certain Iteration", 2)
}

settings_autoci_convergence_cas = {
    "nel": ("Number of active electrons (for CAS)",6), # 
    "norb": ("Number of active orbitals (for CAS)", 7), # 
    "mult": ("Requested multiplicity block", 1), #
    "nroots": ("Number of roots for mult block", 1), # 
    "irrep": ("Requested irrep for mult block", 0), # 
    "nthresh": ("Threshold for lin. dependencies in the IC-CSFs basis", 1e-6), # 
    "D3TPre": ("Density truncation in D3", 1e-14), # 
    "D4TPre": ("Density truncation in D4", 1e-14), # 
    "maxcore": ("Maximum memory limit in MB", 2000), # 
    "printlevel": ("Amount of printing", 3), #  z
    "trafotype": ("Type of integral transformation, 0 is full canonical and 1 is full using RI", [0,1]), # 
    "density": ("Type of density requested",["NONE", "LINEARIZED", "UNRELAXED"]),
}

settings_casscf = {
    "nel": ("Number of active electrons", 6), # 
    "norb": ("Number of active orbitals", 7), # 
    "mult": ("Requested multiplicity block", 1), #
    "nroots": ("Number of roots for mult block", 1), # 
}

# Settings for %coords
settings_coords = {
    "CTyp": ("Type of coordinates used", ["xyz", "internal"]), # Type of coordinates
    "Charge": ("Charge of the module", -2),
    "Mult": ("Multiplicity", 2),
}

settings_scf_general = {
    "maxiter": ("maximum number of iterations until scf convergence", 50),
}

settings_scf_diis = {
    # control of the DIIS procedure
    "DIISStart": ("DIIS start value in Eh", 0.1), # default: 0.2
    "DIISMaxIt": ("The maximum number of cycles after which DIIS will be started irrespective of the error value", 5), # default: 12
    "DIISMaxEq": ("The maximum number of old Fock matrices to remember", 7), # default: 5
    "DIISBFac": ("Factor used to calculate DIIS energy", 1.2), # default: 1.05
    "DIISMaxC": ("", 15.0), # default: 10.0   
}

settings_scf_soscf = {
    "SOSCFStart": ("", 0.1), # default: 0.01
    "SOSCFMaxIt": ("", 5), # default: 1000
}
